"""create roadmap_items table

Revision ID: 17a476603ed4
Revises: 1bc38b531c08
Create Date: 2026-08-16 10:53:41.194170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a476603ed4'
down_revision: Union[str, Sequence[str], None] = '1bc38b531c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=200), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.String(length=20), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('timeline', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_product_id'), 'roadmap_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_items_product_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    # ### end Alembic commands ###
