"""create product_insights table

Revision ID: 1bc38b531c08
Revises: 8ee669edbe8a
Create Date: 2026-08-13 10:55:02.894578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bc38b531c08'
down_revision: Union[str, Sequence[str], None] = '8ee669edbe8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_analyzed_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_insights_product_id'), 'product_insights', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_insights_product_id'), table_name='product_insights')
    op.drop_table('product_insights')
    # ### end Alembic commands ###
