"""add theme_preference and email_notifications_enabled to users

Revision ID: 773043232377
Revises: 17a476603ed4
Create Date: 2026-08-19 06:49:25.878552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773043232377'
down_revision: Union[str, Sequence[str], None] = '17a476603ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('theme_preference', sa.String(length=10), nullable=False, server_default='light'))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # Drop the server defaults after backfilling — new rows use the model's Python-side default instead.
    op.alter_column('users', 'theme_preference', server_default=None)
    op.alter_column('users', 'email_notifications_enabled', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###
