"""add user_type and business_impact to feedback_analysis

Revision ID: 8ee669edbe8a
Revises: 0a3527cdebdb
Create Date: 2026-08-13 04:31:47.031030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee669edbe8a'
down_revision: Union[str, Sequence[str], None] = '0a3527cdebdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_analysis', sa.Column('user_type', sa.String(length=50), nullable=True))
    op.add_column('feedback_analysis', sa.Column('business_impact', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_analysis', 'business_impact')
    op.drop_column('feedback_analysis', 'user_type')
    # ### end Alembic commands ###
